OnlineShop_4M/Controllers/CartController.cs
using System;
using System.Security.Claims;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Identity.UI.Services;
using Microsoft.AspNetCore.Mvc;
using OnlineShop_4M_DataAccess.Data;
using OnlineShop_4M_DataAccess.Repository;
using OnlineShop_4M_DataAccess.Repository.IRepository;
using OnlineShop_4M_Models;
using OnlineShop_4M_Models.ViewModels;
using OnlineShop_4M_Utility;

namespace OnlineShop_4M.Controllers
{
    [Authorize]   // только для авторизованных = кто ввел логин и пароль
	public class CartController : Controller
	{
        
        private IWebHostEnvironment hostEnvironment;
        private IEmailSender emailSender;
        private IProductRepository productRepository;
        private IApplicationUserRepository applicationUserRepository;
        private IInquiryDetailRepository inquiryDetailRepository;
        private IInquiryHeaderRepository inquiryHeaderRepository;


        public CartController(ApplicationDbContext context, IProductRepository productRepository, IApplicationUserRepository applicationUserRepository, IInquiryDetailRepository inquiryDetailRepository, IInquiryHeaderRepository inquiryHeaderRepository, IWebHostEnvironment hostEnvironment, IEmailSender emailSender)
        {
            this.productRepository = productRepository;
            this.applicationUserRepository = applicationUserRepository;
            this.inquiryDetailRepository = inquiryDetailRepository;
            this.inquiryHeaderRepository = inquiryHeaderRepository;
            this.hostEnvironment = hostEnvironment;
            this.emailSender = emailSender;
        }

        public IActionResult Index()
        {
            // создаем список для корзины покупок
            List<ShoppingCart> shoppingCartList = new List<ShoppingCart>();

            // если сессия есть
            if (HttpContext.Session.Get<IEnumerable<ShoppingCart>>(PathManager.SessionCart) != null
                && HttpContext.Session.Get<IEnumerable<ShoppingCart>>(PathManager.SessionCart).Count() > 0)
            {
                // сессия существует!
                // берем лист из сессии и добавляем в лист элемент
                shoppingCartList = HttpContext.Session.Get<List<ShoppingCart>>(PathManager.SessionCart);
            }

            // получаем список идентификаторов
            List<int> productIdCart = shoppingCartList.Select(x => x.ProductId).ToList();

            // извлекаем продукты по id
           // IEnumerable<Product> productList =
             //   productRepository.GetAll(x => productIdCart.Contains(x.Id));
            IEnumerable<Product> productListTemp=productRepository.GetAll(x=>productIdCart.Contains(x.Id));
            List<Product> productList = new List<Product>();
            foreach(var item in shoppingCartList)
            {
                Product productTemp = productListTemp.FirstOrDefault(x => x.Id == item.ProductId);
                productTemp.TempCount = item.Count;
                productList.Add(productTemp);
            }
            return View(productList);
        }

        public IActionResult Remove(int id)
        {
            // создаем списка для его заполнения из сессии
            List<ShoppingCart> shoppingCartList = new List<ShoppingCart>();

            // если сессия есть
            if (HttpContext.Session.Get<IEnumerable<ShoppingCart>>(PathManager.SessionCart) != null
                && HttpContext.Session.Get<IEnumerable<ShoppingCart>>(PathManager.SessionCart).Count() > 0)
            {
                // сессия существует!
                // заполнение листа из сессии
                shoppingCartList = HttpContext.Session.Get<List<ShoppingCart>>(PathManager.SessionCart);
            }

            ShoppingCart item = shoppingCartList.FirstOrDefault(x => x.ProductId == id);

            shoppingCartList.Remove(item);

            // установить обновленный список для сессии
            HttpContext.Session.Set(PathManager.SessionCart, shoppingCartList);

            return RedirectToAction("Index");
        }
        [HttpGet]
        public IActionResult Summary()
        {
            var claimIdentity = (ClaimsIdentity)User.Identity;

            // если пользователь вошел в систему, то определяе объект
            var claim = claimIdentity.FindFirst(ClaimTypes.NameIdentifier);

            // создаем список для корзины покупок
            List<ShoppingCart> shoppingCartList = new List<ShoppingCart>();

            // если сессия есть
            if (HttpContext.Session.Get<IEnumerable<ShoppingCart>>(PathManager.SessionCart) != null
                && HttpContext.Session.Get<IEnumerable<ShoppingCart>>(PathManager.SessionCart).Count() > 0)
            {
                // сессия существует!
                // берем лист из сессии и добавляем в лист элемент
                shoppingCartList = HttpContext.Session.Get<List<ShoppingCart>>(PathManager.SessionCart);
            }

            // получаем список идентификаторов всех продуктов
            List<int> productIdCart = shoppingCartList.Select(x => x.ProductId).ToList();

            // извлекаем продукты по id
            IEnumerable<Product> productListTemp = productRepository.GetAll(x => productIdCart.Contains(x.Id));
            List<Product> productList = new List<Product>();
            foreach (var item in shoppingCartList)
            {
                Product productTemp = productListTemp.FirstOrDefault(x => x.Id == item.ProductId);
                productTemp.TempCount = item.Count;
                productList.Add(productTemp);
            }
            ProductUserViewModel viewModel = new ProductUserViewModel()
            {
                ApplicationUser = applicationUserRepository.FirstOrDefault(x => x.Id == claim.Value),
                ProductList = productList.ToList()
            };

            return View(viewModel);
        }
        public IActionResult InquiryConfirmation()
        {
            HttpContext.Session.Clear();
            return View();
        }
        [HttpPost]
        public async Task<IActionResult> SummaryPost(ProductUserViewModel productUserViewModel)
        {
            var indetyClaims = (ClaimsIdentity)User.Identity;
            var claim=indetyClaims?.FindFirst(ClaimTypes.NameIdentifier);
            var pathTemplate = hostEnvironment.WebRootPath + PathManager.TemplatesPath + "inquiry.html";

            var bodyHtml=await System.IO.File.ReadAllTextAsync(pathTemplate);

            var textProducts = "";
            foreach(var product in productUserViewModel.ProductList)
            {
                textProducts += $"- Name: {product.Name} " + $"<span style='font-size: 14px; color: green' >(ID: {product.Id})</span>" + "<br>";
            }
            var body = string.Format(bodyHtml, productUserViewModel.ApplicationUser.FullName, productUserViewModel.ApplicationUser.PhoneNumber, textProducts);
            await emailSender.SendEmailAsync(productUserViewModel.ApplicationUser.Email, "Новый Заказ", body);
            var inquiryHeader=new InquiryHeader()
            {
                ApplicationUserId=claim.Value,
                ApplicationUser =applicationUserRepository.FirstOrDefault(x=>x.Id==claim.Value),
                FullName =productUserViewModel.ApplicationUser.FullName,
                Email=productUserViewModel.ApplicationUser.Email,
                PhoneNumber=productUserViewModel.ApplicationUser.PhoneNumber ?? "+70000000000",
                InquiryDate=DateTime.Now
            };
            inquiryHeaderRepository.Add(inquiryHeader);
            inquiryHeaderRepository.Save();
            foreach(var product in productUserViewModel.ProductList)
            {
                var inquiryDetail = new InquiryDetail() 
                { 
                    InquiryHeaderId=inquiryHeader.Id,
                    ProductId=product.Id
                };
                inquiryDetailRepository.Add(inquiryDetail);
            }
            inquiryDetailRepository.Save();
            return RedirectToAction("InquiryConfirmation");
        }
    }
}

OnlineShop_4M/Controllers/CategoryController.cs
using System;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using OnlineShop_4M_DataAccess.Data;
using OnlineShop_4M_Models;
using OnlineShop_4M_Utility;
using OnlineShop_4M_DataAccess.Repository.IRepository;
 

namespace OnlineShop_4M.Controllers
{
	[Authorize(Roles = PathManager.AdminRole)]
	public class CategoryController : Controller
	{
		//private ApplicationDbContext context;
		private ICategoryRepository categoryRepository;

		public CategoryController(ICategoryRepository categoryRepository)
		{
			
			this.categoryRepository = categoryRepository;
		}

        public IActionResult Index()
		{
            List<Category> categoryList=categoryRepository.GetAll().ToList();
			

			return View(categoryList);
		}

		[HttpGet]
		public IActionResult Create()
		{
			return View();
		}

		[HttpPost]
		public IActionResult Create(Category category)
		{
			if (ModelState.IsValid)
			{
				categoryRepository.Add(category);
				categoryRepository.Save();


                return RedirectToAction("Index");
            }

			return View(category);
		}

		[HttpGet]
		public IActionResult Edit(int? id)
		{
			if (id == null || id == 0)
			{
				return NotFound();
			}
			var category = categoryRepository.Find(id.Value);

			return View(category);
		}

		[HttpPost]
		public IActionResult Edit(Category category)
		{
			if (ModelState.IsValid)
			{
				categoryRepository.Update(category);
				categoryRepository.Save();
				

				return RedirectToAction("Index");
			}

			return View(category);
		}

        public IActionResult Delete(int? id)
        {
            if (id == null || id == 0)
            {
                return NotFound();
            }

            var category =categoryRepository.Find(id.Value);

			if (category == null)
			{
                return NotFound();
            }

            return View(category);
        }

		[HttpPost]
		public IActionResult Delete(Category category)
		{
			int id = category.Id;

			var categoryFromBase = categoryRepository.Find(id);

			if (categoryFromBase == null)
			{
				return NotFound();
			}

			categoryRepository.Remove(categoryFromBase);
            categoryRepository.Save();

			return RedirectToAction("Index");
		}
    }
}

OnlineShop_4M/Controllers/CompanyController.cs
using System;
using Microsoft.AspNetCore.Authorization;
using System.Data;
using Microsoft.AspNetCore.Mvc;
using OnlineShop_4M_DataAccess.Data;
using OnlineShop_4M_Models;
using OnlineShop_4M_Utility;
using OnlineShop_4M_DataAccess.Repository.IRepository;

namespace OnlineShop_4M.Controllers
{
    [Authorize(Roles = PathManager.AdminRole)]
    public class CompanyController : Controller
    {
        private ICompanyRepository companyRepository;
    

        public CompanyController(ApplicationDbContext context, ICompanyRepository companyRepository)
        {
            this.companyRepository=companyRepository;
            
        }

        public IActionResult Index()
        {
            List<Company> companyList = companyRepository.GetAll().ToList();

            return View(companyList);
        }


        [HttpGet]
        public IActionResult Create()
        {
            return View();
        }

        [HttpPost]
        public IActionResult Create(Company company)
        {
            if (ModelState.IsValid)
            {
                companyRepository.Add(company);
                companyRepository.Save();

                return RedirectToAction("Index");
            }

            return View(company);
        }

        [HttpGet]
        public IActionResult Edit(int? id)
        {
            if (id == null || id == 0)
            {
                return NotFound();
            }

            var company = companyRepository.Find(id.Value);

            return View(company);
        }

        [HttpPost]
        public IActionResult Edit(Company company)
        {
            if (ModelState.IsValid)
            {
                companyRepository.Update(company);   // !!! EF UPDATE
                companyRepository.Save();

                return RedirectToAction("Index");
            }

            return View(company);
        }

        public IActionResult Delete(int? id)
        {
            if (id == null || id == 0)
            {
                return NotFound();
            }

            var company = companyRepository.Find(id.Value);

            if (company == null)
            {
                return NotFound();
            }

            return View(company);
        }

        [HttpPost]
        public IActionResult Delete(Company company)
        {
            int id = company.Id;

            var companyFromBase = companyRepository.Find(id);

            if (companyFromBase == null)
            {
                return NotFound();
            }

            companyRepository.Remove(companyFromBase);
            companyRepository.Save();

            return RedirectToAction("Index");
        }
    }
}

OnlineShop_4M/Controllers/InquiryController.cs
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using OnlineShop_4M_DataAccess.Repository.IRepository;
using OnlineShop_4M_Models;
using OnlineShop_4M_Models.ViewModels;
using OnlineShop_4M_Utility;

namespace OnlineShop_4M.Controllers
{
    [Authorize(Roles =PathManager.AdminRole)]
    public class InquiryController : Controller
    {
        private IInquiryHeaderRepository inquiryHeaderRepository;
        private IInquiryDetailRepository inquiryDetailRepository;
        [BindProperty]
        public InquiryViewModel InquiryViewModel { get; set; }
        public InquiryController(IInquiryHeaderRepository inquiryHeaderRepository, IInquiryDetailRepository inquiryDetailRepository)
        {
            this.inquiryHeaderRepository = inquiryHeaderRepository;
            this.inquiryDetailRepository = inquiryDetailRepository;
        }
        public IActionResult Details(int id)
        {
            InquiryViewModel = new InquiryViewModel()
            {
                InquiryHeader = inquiryHeaderRepository.FirstOrDefault(x => x.Id == id),
                InquiryDetails = inquiryDetailRepository.GetAll(x => x.InquiryHeaderId == id, includeProperties: "Product")
            };
            return View(InquiryViewModel);
        }
        [HttpPost]
        public IActionResult Delete()
        {
            InquiryHeader inquiryHeader=inquiryHeaderRepository.FirstOrDefault(x=>x.Id==InquiryViewModel.InquiryHeader.Id);
            IEnumerable<InquiryDetail> inquiryDetails = inquiryDetailRepository.GetAll(x => x.InquiryHeaderId ==InquiryViewModel.InquiryHeader.Id);
            inquiryDetailRepository.RemoveRange(inquiryDetails);
            inquiryHeaderRepository.Remove(inquiryHeader);
            inquiryDetailRepository.Save();
            return RedirectToAction("Index");
        }
        [HttpPost]
        public IActionResult ConvertToCart()
        {
            List<ShoppingCart> shoppingCarts = new List<ShoppingCart>();

            InquiryViewModel.InquiryDetails=inquiryDetailRepository.GetAll(x=>x.InquiryHeaderId==InquiryViewModel.InquiryHeader.Id);

            foreach (var item in InquiryViewModel.InquiryDetails)
            {
                ShoppingCart shoppingCart = new ShoppingCart()
                {
                    ProductId = item.ProductId
                };
                shoppingCarts.Add(shoppingCart);
            }
            HttpContext.Session.Clear();
            HttpContext.Session.Set(PathManager.SessionCart,shoppingCarts);
            HttpContext.Session.Set(PathManager.SessionInquiryId, InquiryViewModel.InquiryHeader.Id);
            return RedirectToAction("Index","Cart");
        }
        public IActionResult Index()
        {
            return View();
        }
        [HttpGet]
        public IActionResult GetInquiryList() 
        {
            var result = Json( new {data=inquiryHeaderRepository.GetAll()});
            return result;
        }
    }
}

OnlineShop_4M/Views/Shared/_Layout.cshtml
@using OnlineShop_4M_Utility;
@using OnlineShop_4M_Models;
@inject IHttpContextAccessor HttpContextAccessor

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - OnlineShop_4M</title>

    <link rel="stylesheet" href="https://cdn.datatables.net/2.0.7/css/dataTables.dataTables.min.css"/>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/OnlineShop_4M.styles.css" asp-append-version="true" />

    <!-- include summernote css/js -->
    <link href="https://cdn.jsdelivr.net/npm/summernote@0.8.18/dist/summernote.min.css" rel="stylesheet">

</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">OnlineShop_4M</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">

                    <partial name="_LoginPartial" />

                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>

                        @if (User.IsInRole(PathManager.AdminRole))
                        {
                            <li class="nav-item dropdown">
                                <a class="nav-link dropdown-toggle" href="#" role="button" data-bs-toggle="dropdown" aria-expanded="false">
                                    Действия
                                </a>
                                <ul class="dropdown-menu">
                                    <li>
                                        <a class="text-dark dropdown-item" asp-area="" asp-controller="Category" asp-action="Index">Category</a>
                                    </li>
                                    <li>
                                        <a class="text-dark dropdown-item" asp-area="" asp-controller="Company" asp-action="Index">Company</a>
                                    </li>
                                    <li>
                                        <a class="text-dark dropdown-item" asp-area="" asp-controller="Product" asp-action="Index">Product</a>
                                    </li>

                                    <li><hr class="dropdown-divider"></li>

                                    <li>
                                        <a class="text-dark dropdown-item" asp-area="Identity" asp-page="/Account/Register">Create Admin User</a>
                                    </li>
                                </ul>
                            </li>
                            <li class="nav-item dropdown">
                                <a class="nav-link dropdown-toggle" href="#" role="button" data-bs-toggle="dropdown" aria-expanded="false">
                                    Управление заказами
                                </a>
                                <ul class="dropdown-menu">
                                    <li>
                                        <a class="text-dark dropdown-item" asp-area="" asp-controller="Inquiry" asp-action="Index">Inquiry</a>
                                    </li>
                                    
                                </ul>
                            </li>
                        }


                        <li class="nav-item">
                            @if (HttpContextAccessor.HttpContext.Session.
                              Get<List<ShoppingCart>>(PathManager.SessionCart) != null)
                            {
                                var count = HttpContextAccessor.HttpContext.Session.
                                Get<List<ShoppingCart>>(PathManager.SessionCart).Count;

                                <a class="nav-link text-dark" asp-controller="Cart" asp-action="Index">
                                    Cart (@count)
                                </a>
                            }
                            else
                            {
                                <a class="nav-link text-dark" href="#">
                                    Cart (0)
                                </a>
                            }

                        </li>

                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2024 - OnlineShop_4M - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>

    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    <script src="https://cdn.jsdelivr.net/npm/sweetalert2@11"></script>
    <script src="https://cdn.datatables.net/2.0.7/js/dataTables.min.js"></script>

    <script src="https://cdn.jsdelivr.net/npm/summernote@0.8.18/dist/summernote.min.js"></script>

    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>